# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - 'v*.*.*'

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- script: |
    python3 -m pip install git+https://github.com/acre-bdd/acre-cli.git
  displayName: 'install greenhouse-cli'

- script: |
    acre init
    acre build
  displayName: 'initialize and build acre image'

- script: |
    acre run features/
  displayName: 'run acre tests'

