name: Makefile CI

on:
  push:
    branches: [ master, branches/query ]
  pull_request:
    branches: [ master, branches/query ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: acre-test
    
    - name: install and initialise acre
      run: |
        python3 -m pip install git+https://github.com/acre-bdd/acre-cli.git
        acre init

    - name: run acre-tests
      run: |
        cd acre-test
        acre run --noterm features/*
        
      


